INSERT INTO users (name, age) VALUES ("Brenda", 20);
INSERT INTO users (name, age) VALUES ("LaTisha", 21);
INSERT INTO users (name, age) VALUES ("Linda", 22);
INSERT INTO users (name, age) VALUES ("Felica", 23);
INSERT INTO users (name, age) VALUES ("Dawn", 24);
INSERT INTO users (name, age) VALUES ("LeShaun", 25);
INSERT INTO users (name, age) VALUES ("Ines", 26);
INSERT INTO users (name, age) VALUES ("Alicia", 27);
INSERT INTO users (name, age) VALUES ("Teresa", 28);
INSERT INTO users (name, age) VALUES ("Monica", 29);
INSERT INTO users (name, age) VALUES ("Sharron", 30);
INSERT INTO users (name, age) VALUES ("Nicki", 31);
INSERT INTO users (name, age) VALUES ("Lisa", 32);
INSERT INTO users (name, age) VALUES ("Veronica", 33);
INSERT INTO users (name, age) VALUES ("Karen", 34);
INSERT INTO users (name, age) VALUES ("Vicky", 35);
INSERT INTO users (name, age) VALUES ("Tonya", 36);
INSERT INTO users (name, age) VALUES ("Diane", 37);
INSERT INTO users (name, age) VALUES ("Lori", 38);
INSERT INTO users (name, age) VALUES ("Carla", 39);

INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("This", "Medical", 100, "2020-01-01", "2020-12-31");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Is", "Exploration", 200, "2020-01-2", "2020-12-30");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("The", "Discovery", 300, "2020-01-3", "2020-12-29");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("List", "Help", 400, "2020-01-3", "2020-12-28");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Of", "Donation", 500, "2020-01-4", "2020-12-27");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("New", "Archaelogical", 600, "2020-01-5", "2020-12-26");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Projects", "Restoration", 700, "2020-01-6", "2020-12-25");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("And", "Science", 800, "2020-01-7", "2020-12-24");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Their", "Math", 900, "2020-01-8", "2020-12-23");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Titles", "Art", 100, "2020-01-9", "2020-12-22");

INSERT INTO pledges (amount, user_id, project_id) VALUES ( 10, 1, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES ( 20, 2, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES ( 30, 3, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES ( 40, 4, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES ( 50, 5, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES ( 60, 6, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES ( 70, 7, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES ( 80, 8, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES ( 90, 9, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES ( 100, 10, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES ( 200, 11, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES ( 300, 12, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES ( 400, 13, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES ( 500, 14, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES ( 400, 15, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES ( 300, 16, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES ( 200, 17, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES ( 100, 18, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES ( 90, 19, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES ( 80, 20, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES ( 70, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES ( 60, 2, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES ( 50, 3, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES ( 60, 4, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES ( 70, 5, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES ( 80, 6, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES ( 90, 7, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES ( 100, 8, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES ( 200, 9, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES ( 300, 10, 10);